name: Node.js CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}
      
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cj7t4p45kgrc73c7gtag"
        retries: 20
        wait: 16000
        sleep: 30000




      
    
